---
include:
  - project: digital-retail/ci-reuse/templates/pipeline-cross-templates
    ref: main
    file: .gitlab-ci-node.yml
variables:
  DIGITAL_RETAIL: "true"
  NODE_VERSION: node:22.15.0-alpine3.20
  UNIT_TEST_COMMAND: npm run test:unit
  INTEGRATION_TEST_COMMAND: npm run test:integration
deploy:falabella:staging:
  environment:
    name: falabella-staging
deploy:falabella:prod:
  environment:
    name: falabella-production
