---
include:
  - project: digital-retail/ci-reuse/templates/pipeline-cross-templates
    ref: main
    file: .gitlab-ci-node.yml
variables:
  DIGITAL_RETAIL: "true"
  NODE_VERSION: node:20.18.1-alpine3.21
  UNIT_TEST_COMMAND: ""
  INTEGRATION_TEST_COMMAND: ""
deploy:falabella:staging:
  rules:
    - !reference [.deploy_always_ci_rules, rules]
  environment:
    name: falabella-staging
deploy:falabella:production:
  environment:
    name: falabella-production
