image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}

include:
  - component: gitlab.falabella.tech/falabella-infrastructure-standards/gitlab-components/workload-identity-federation/auth@1
  - ".gitlab/cd/cloud_run.yml"

stages:
  - Build
  - Deploy
