name: CI/CD Pipeline with GHCR

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/altair-svc:${{ github.sha }} .
          docker tag ghcr.io/${{ secrets.GHCR_USERNAME }}/altair-svc:${{ github.sha }} ghcr.io/${{ secrets.GHCR_USERNAME }}/altair-svc:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/altair-svc:${{ github.sha }}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/altair-svc:latest

  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

      - name: Deploy Docker Image to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << 'EOF'
          docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password ${{ secrets.GHCR_TOKEN }}
          docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/altair-svc:latest
          cd ~
          docker compose down
          docker compose up -d
          EOF